FROM python:3.12-slim

WORKDIR /reportai


RUN pip install sqlalchemy passlib passlib[bcrypt] fastapi[all] groq pandas pydantic sqlparse uvicorn mysql-connector-python python-dotenv

COPY . .
EXPOSE 8000

CMD ["uvicorn", "faspi:app", "--reload"]
